package actions

import (
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/mi-subbotin/lazyagent/internal/model"
	"github.com/mi-subbotin/lazyagent/internal/store"
)

// ShareConflict describes one target whose existing on-disk content
// would be replaced by a Place. Kind is a human label ("directory" /
// "file" / "symlink" / "entry") so the UI can show the user what they're
// about to destroy without re-statting.
//
// Name kept from the legacy Share API even though Share itself is gone:
// renaming would touch the TUI overlay and every test that asserts the
// shape, while the struct is by-value copy-friendly across packages.
type ShareConflict struct {
	Target model.Origin
	Path   string
	Kind   string
}

// canShareKind reports whether (Kind, Storage) has a canonical library
// layout. Entry-shaped items are routed through placeEntry instead of
// the library and gated separately by canPlaceEntryKind.
func canShareKind(k model.Kind, s model.Storage) bool {
	if s == model.StorageEntry {
		return false
	}
	switch k {
	case model.KindSkill, model.KindAgent, model.KindPrompt, model.KindMemory:
		return true
	}
	return false
}

// canProjectTo reports whether the canonical shape for kind can be
// projected to target. Includes both lossless symlink projections and
// the lossy generated-file projections introduced in PRI-68 (md →
// codex profile entry, md → gemini TOML file). Combos that have no
// projector at all stay false — the TUI greys those cells out.
func canProjectTo(k model.Kind, target model.Origin) bool {
	switch k {
	case model.KindSkill, model.KindMemory:
		return true
	case model.KindAgent:
		// All three tools supported: Claude/Gemini lossless,
		// Codex via md→profile entry generator.
		return true
	case model.KindPrompt:
		// All three tools supported: Claude/Codex lossless,
		// Gemini via md→TOML generator.
		return true
	}
	return false
}

// isLossyProjection reports whether projecting `k` to `target` requires
// a format conversion (md → codex profile entry, md → gemini TOML).
// The Place picker labels these cells `(lossy)` so users know edits
// against the projected target won't survive a Resync canonical-wins.
func isLossyProjection(k model.Kind, target model.Origin) bool {
	switch k {
	case model.KindAgent:
		return target == model.OriginCodex
	case model.KindPrompt:
		return target == model.OriginGemini
	}
	return false
}

// IsLossyProjection is the exported form for the TUI picker.
func IsLossyProjection(k model.Kind, target model.Origin) bool {
	return isLossyProjection(k, target)
}

// canonicalBodyName delegates to store.CanonicalBodyName; the layout
// is owned by the store package so adapters, Place, and drift detection
// all agree on a single source of truth.
func canonicalBodyName(k model.Kind) (string, bool) {
	return store.CanonicalBodyName(k)
}

// projectionPath returns the per-tool path where the canonical item
// should be projected. Same routing the legacy Share / Reshare used —
// shared with Place via the unified projection diff.
func projectionPath(k model.Kind, name string, target model.Origin, scope model.Scope, projectDir string) (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	switch k {
	case model.KindSkill:
		root, err := skillRoot(home, projectDir, target, scope)
		if err != nil {
			return "", err
		}
		return filepath.Join(root, name), nil
	case model.KindAgent:
		root, err := toolRoot(home, projectDir, target, scope)
		if err != nil {
			return "", err
		}
		return filepath.Join(root, "agents", name+".md"), nil
	case model.KindPrompt:
		switch target {
		case model.OriginClaude:
			root, err := toolRoot(home, projectDir, target, scope)
			if err != nil {
				return "", err
			}
			return filepath.Join(root, "commands", name+".md"), nil
		case model.OriginCodex:
			if scope == model.ScopeLocal && projectDir == "" {
				return "", ErrNoProject
			}
			base := home
			if scope == model.ScopeLocal {
				base = projectDir
			}
			return filepath.Join(base, ".codex", "prompts", name+".md"), nil
		case model.OriginGemini:
			// Gemini commands are TOML files, not symlinks. The path
			// here is the "file we'd write" — Place's lossy branch
			// still writes through generated bytes rather than EnsureLink.
			root, err := toolRoot(home, projectDir, target, scope)
			if err != nil {
				return "", err
			}
			return filepath.Join(root, "commands", name+".toml"), nil
		}
		return "", fmt.Errorf("prompt target %s has no projection path", target)
	case model.KindMemory:
		return memoryTargetPath(target, scope, home, projectDir)
	}
	return "", fmt.Errorf("no projection path for kind %s", k)
}

// skillRoot returns the directory that holds <name>/SKILL.md for a
// given (origin, scope). Codex skills live under .agents/skills/ — a
// sibling of .codex/, not a subdirectory — so its layout differs from
// Claude (.claude/skills) and Gemini (.gemini/skills).
func skillRoot(home, projectDir string, origin model.Origin, scope model.Scope) (string, error) {
	if scope == model.ScopeLocal && projectDir == "" {
		return "", ErrNoProject
	}
	base := home
	if scope == model.ScopeLocal {
		base = projectDir
	}
	switch origin {
	case model.OriginClaude:
		return filepath.Join(base, ".claude", "skills"), nil
	case model.OriginCodex:
		return filepath.Join(base, ".agents", "skills"), nil
	case model.OriginGemini:
		return filepath.Join(base, ".gemini", "skills"), nil
	}
	return "", fmt.Errorf("unknown origin %v", origin)
}

// toolRoot returns the per-tool home (<base>/.claude, .codex, .gemini)
// for a given (origin, scope). agents/ and commands/ subdirectories
// hang off this root.
func toolRoot(home, projectDir string, origin model.Origin, scope model.Scope) (string, error) {
	if scope == model.ScopeLocal && projectDir == "" {
		return "", ErrNoProject
	}
	var sub string
	switch origin {
	case model.OriginClaude:
		sub = ".claude"
	case model.OriginCodex:
		sub = ".codex"
	case model.OriginGemini:
		sub = ".gemini"
	default:
		return "", fmt.Errorf("unknown origin %v", origin)
	}
	if scope == model.ScopeGlobal {
		return filepath.Join(home, sub), nil
	}
	return filepath.Join(projectDir, sub), nil
}

// memoryTargetPath returns the canonical memory-file location for a
// (target, scope) pair. Each tool uses a different filename
// (CLAUDE.md / AGENTS.md / GEMINI.md) and a slightly different relative
// path.
func memoryTargetPath(target model.Origin, scope model.Scope, home, projectDir string) (string, error) {
	if scope == model.ScopeLocal && projectDir == "" {
		return "", ErrNoProject
	}
	switch target {
	case model.OriginClaude:
		if scope == model.ScopeGlobal {
			return filepath.Join(home, ".claude", "CLAUDE.md"), nil
		}
		return filepath.Join(projectDir, "CLAUDE.md"), nil
	case model.OriginCodex:
		if scope == model.ScopeGlobal {
			return filepath.Join(home, ".codex", "AGENTS.md"), nil
		}
		return filepath.Join(projectDir, "AGENTS.md"), nil
	case model.OriginGemini:
		if scope == model.ScopeGlobal {
			return filepath.Join(home, ".gemini", "GEMINI.md"), nil
		}
		return filepath.Join(projectDir, "GEMINI.md"), nil
	}
	return "", fmt.Errorf("unknown target origin %v", target)
}

// diffOrigin returns elements in a not present in b. Small helper used
// by SyncAll's add/remove math; kept origin-typed because the planner
// works in origin-space rather than (origin, scope) tuples.
func diffOrigin(a, b []model.Origin) []model.Origin {
	bset := map[model.Origin]bool{}
	for _, x := range b {
		bset[x] = true
	}
	var out []model.Origin
	for _, x := range a {
		if !bset[x] {
			out = append(out, x)
		}
	}
	return out
}

// moveDir does os.Rename, falling back to copy+delete when the source
// and destination live on different filesystems (cross-device link).
func moveDir(src, dst string) error {
	if err := os.Rename(src, dst); err == nil {
		return nil
	}
	if err := copyDir(src, dst); err != nil {
		return err
	}
	return os.RemoveAll(src)
}

// moveFile does os.Rename with the same cross-device fallback.
func moveFile(src, dst string) error {
	if err := os.Rename(src, dst); err == nil {
		return nil
	}
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	if _, err := io.Copy(out, in); err != nil {
		out.Close()
		return err
	}
	if err := out.Close(); err != nil {
		return err
	}
	return os.Remove(src)
}
